language: node_js
node_js:
- '0.11'
before_install: npm install -g grunt-cli
install:
  - npm install
  - sudo apt-get install s3cmd
before_script: grunt
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJQCFHOZKLTA7DIZQ
  secret_access_key:
    secure: twvvMsBOB0D/TN1A4902Fm0ublxEFu93Mz2WWMgjRt+sQlMw+dblbYcRJ/PTL+9+OldYWe0/SIY/qYMrV9m37KpwqFNl7SxBUr7o67NAgO879dQr3BVEBhfpnDP9ECsRvaoEqoWDN3qbVe4ZSbQNNBIrqZYUhkTq2Tox83JdOH8=
  bucket: assets.bjerkness.net
  region: us-west-2
  upload-dir: revealjs
  local-dir: dist
  acl: !ruby/string:HighLine::String public_read
