language: node_js

node_js:
  - "0.11"

before_script:
- npm update
- npm install -g grunt-cli

deploy:
  provider: s3
  access_key_id: AKIAIFUVCGYAEHLVSEUA
  secret_access_key:
    secure: VHP0UqirQSZU+S/ZgYFpTP5aNYX3zWGfx7vzOQAPs/ypAhpL0xnbbj3dArw7dGZ45rDYagWsqgM6fMEm7+dIK7EXcYkUQb9BIao700xQe95jcT5rI7xMmZSPPAXg1MIuj9lKy9E2djOFRRnnidpM6vMPjT5wpszMchCS/oRjTYk=
  bucket: assets.bjerkness.net
  upload-dir: revealjs
  acl: !ruby/string:HighLine::String public_read
  on:
    repo: mbjerkness/reveal.js
